# Site settings
title: Presentations
description: >
  This site is built with [Jekyll](https://jekyllrb.com). Each individual presentation is capable
  of utilizing the [WordPress REST API](http://v2.wp-api.org) to load slides from a remote site (even if
  not all of them actually do). [Remark](https://remarkjs.com/) is used to convert the slides from
  Markdown to pretty content.

  Curious about how it works? Check out the
  [repository on GitHub](https://github.com/JPry/presentations).

# the subpath of your site, e.g. /blog/
baseurl: "/presentations"

# the base hostname & protocol for your site
url: "https://jpry.github.io"

twitter_username: JPry
github_username:  JPry
permalink: '/:title/'

# Build settings
markdown: kramdown
exclude:
    - README.md
    - Gemfile
    - Gemfile.lock

timezone: America/New_York

defaults:
    -
        scope:
            path: ''
        values:
            layout: presentation
            local_js: false
    -
        scope:
            path: ''
            type: drafts
        values:
            local_js: true
