# Site settings
title: Presentations
description: >
  This site is built with [Jekyll](http://jekyllrb.com). Each individual presentation utilizes
  the [WordPress REST API](http://v2.wp-api.org) to load slides from a remote site.
  [Remark](http://remarkjs.com/) is used to convert the slides from Markdown to pretty content.
  Curious about how it works? Check out the [repository on GitHub](https://github.com/JPry/presentations).
baseurl: "/presentations" # the subpath of your site, e.g. /blog/
url: "http://jpry.github.io" # the base hostname & protocol for your site
twitter_username: JPry
github_username:  JPry

# Build settings
markdown: kramdown
